In [160]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\rohit\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\rohit\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\rohit\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\rohit\anaconda3\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\rohit\anaconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\rohit\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [162]:
import pandas as pd
import numpy as np
import ast
import nltk

In [2]:
movie1 = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movie1.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [4]:
credits= pd.read_csv('tmdb_5000_credits.csv')

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [7]:
credits=credits.rename(columns={'movie_id': 'id'})

In [8]:
movies=movie1.merge(credits,on='id')

In [9]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew'],
      dtype='object')

In [10]:
movies=movies.drop(['budget','homepage','original_language','original_title','production_countries','release_date',
                    'revenue','runtime','spoken_languages', 'status','vote_average','vote_count','popularity','tagline'],axis=1)

In [11]:
movies.columns

Index(['genres', 'id', 'keywords', 'overview', 'production_companies',
       'title_x', 'title_y', 'cast', 'crew'],
      dtype='object')

In [12]:
movies=movies.drop('title_y',axis=1)

In [13]:
movies=movies.rename(columns={'title_x' : 'title'})

In [14]:
movies.columns

Index(['genres', 'id', 'keywords', 'overview', 'production_companies', 'title',
       'cast', 'crew'],
      dtype='object')

In [15]:
movies.head()

,genres,id,keywords,overview,production_companies,title,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
movies.isnull().sum()

genres                  0
id                      0
keywords                0
overview                3
production_companies    0
title                   0
cast                    0
crew                    0
dtype: int64

In [17]:
movies.dropna(inplace=True)

In [18]:
movies.duplicated().sum()

0

In [19]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
def convert (obj):
    L =[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [21]:
movies['genres'] = movies['genres'].apply(convert)

In [22]:
movies.head()

,genres,id,keywords,overview,production_companies,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies.iloc[1].keywords

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [24]:
movies['keywords'] = movies['keywords'].apply(convert)

In [25]:
movies.head()

,genres,id,keywords,overview,production_companies,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
movies.iloc[1].production_companies

'[{"name": "Walt Disney Pictures", "id": 2}, {"name": "Jerry Bruckheimer Films", "id": 130}, {"name": "Second Mate Productions", "id": 19936}]'

In [27]:
def convert1 (obj):
    L =[]
    count = 0
    for i in ast.literal_eval(obj):
        if count != 2:
            L.append(i['name'])
            count+=1 
        else:
            break
    return L

In [28]:
movies['production_companies']=movies['production_companies'].apply(convert1)

In [29]:
def convert2 (obj):
    L =[]
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            L.append(i['name'])
            count+=1 
        else:
            break
    return L

In [30]:
movies['cast']=movies['cast'].apply(convert2)

In [31]:
def fetch_director(obj):
    L =[]  
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
            L.append(i['name'])
            break
    return L

In [32]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [33]:
movies.head()

,genres,id,keywords,overview,production_companies,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Ingenious Film Partners, Twentieth Century Fo...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Walt Disney Pictures, Jerry Bruckheimer Films]",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Columbia Pictures, Danjaq]",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Legendary Pictures, Warner Bros.]",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",[Walt Disney Pictures],John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [34]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [35]:
movies.head()

,genres,id,keywords,overview,production_companies,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Ingenious Film Partners, Twentieth Century Fo...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Walt Disney Pictures, Jerry Bruckheimer Films]",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Columbia Pictures, Danjaq]",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Legendary Pictures, Warner Bros.]",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",[Walt Disney Pictures],John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [36]:
movies.columns

Index(['genres', 'id', 'keywords', 'overview', 'production_companies', 'title',
       'cast', 'crew'],
      dtype='object')

In [37]:
movies = movies[['id', 'title', 'genres', 'overview', 'production_companies', 'cast', 'crew','keywords']]

In [38]:
movies.head()

,id,title,genres,overview,production_companies,cast,crew,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[Ingenious Film Partners, Twentieth Century Fo...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[Walt Disney Pictures, Jerry Bruckheimer Films]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[Columbia Pictures, Danjaq]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[Legendary Pictures, Warner Bros.]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[based on novel, mars, medallion, space travel..."

In [80]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['overview']=movies['overview'].apply(lambda x:[i.replace(" ","") for i in x])
movies['production_companies']=movies['production_companies'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [82]:
movies.head()

,id,title,genres,overview,production_companies,cast,crew,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[WaltDisneyPictures, JerryBruckheimerFilms]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[ColumbiaPictures, Danjaq]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[LegendaryPictures, WarnerBros.]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...",[WaltDisneyPictures],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [85]:
movies.columns

Index(['id', 'title', 'genres', 'overview', 'production_companies', 'cast',
       'crew', 'keywords'],
      dtype='object')

In [93]:
movies['tags']= movies['genres']+movies['overview']+ movies['production_companies']+movies['cast']+movies['crew']+movies['keywords']

In [96]:
movies.head()

,id,title,genres,overview,production_companies,cast,crew,keywords,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[IngeniousFilmPartners, TwentiethCenturyFoxFil...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction, I..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[WaltDisneyPictures, JerryBruckheimerFilms]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action, Captain, Barbossa..."
2,206647,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[ColumbiaPictures, Danjaq]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime, A, cryptic, message..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[LegendaryPictures, WarnerBros.]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller, Following, th..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...",[WaltDisneyPictures],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction, John, Cart..."

In [98]:
new_df=movies[['id', 'title','tags']]

In [100]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, I..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, Captain, Barbossa..."
2,206647,Spectre,"[Action, Adventure, Crime, A, cryptic, message..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, Following, th..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, John, Cart..."

In [104]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\rohit\AppData\Local\Temp\ipykernel_21496\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [106]:
new_df.head()

,id,title,tags
0,19995,Avatar,Action Adventure Fantasy ScienceFiction In the...
1,285,Pirates of the Caribbean: At World's End,"Adventure Fantasy Action Captain Barbossa, lon..."
2,206647,Spectre,Action Adventure Crime A cryptic message from ...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller Following the deat...
4,49529,John Carter,Action Adventure ScienceFiction John Carter is...

In [110]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\rohit\AppData\Local\Temp\ipykernel_21496\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [164]:
from nltk.stem.porter import PorterStemmer

In [168]:
ps = PorterStemmer()

In [196]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [202]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\rohit\AppData\Local\Temp\ipykernel_21496\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [203]:
from sklearn.feature_extraction.text import CountVectorizer

In [204]:
cv= CountVectorizer(max_features =4800,stop_words='english')

In [205]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [206]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [220]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [208]:
new_df.iloc[0].tags

'action adventur fantasi sciencefict in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. ingeniousfilmpartn twentiethcenturyfoxfilmcorpor samworthington zoesaldana sigourneyweav jamescameron cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [216]:
stem('action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. ingeniousfilmpartners twentiethcenturyfoxfilmcorporation samworthington zoesaldana sigourneyweaver jamescameron cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d')

'action adventur fantasi sciencefict in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. ingeniousfilmpartn twentiethcenturyfoxfilmcorpor samworthington zoesaldana sigourneyweav jamescameron cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d'

In [222]:
from sklearn.metrics.pairwise import cosine_similarity

In [224]:
cosine_similarity(vectors)

array([[1.        , 0.08119979, 0.08492078, ..., 0.04529108, 0.        ,
        0.        ],
       [0.08119979, 1.        , 0.05976143, ..., 0.02390457, 0.        ,
        0.02577696],
       [0.08492078, 0.05976143, 1.        , ..., 0.025     , 0.        ,
        0.        ],
       ...,
       [0.04529108, 0.02390457, 0.025     , ..., 1.        , 0.04082483,
        0.04313311],
       [0.        , 0.        , 0.        , ..., 0.04082483, 1.        ,
        0.08804509],
       [0.        , 0.02577696, 0.        , ..., 0.04313311, 0.08804509,
        1.        ]])

In [230]:
similarity=cosine_similarity(vectors)

In [234]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (1213, 0.29986532511593345),
 (507, 0.2710098294963041),
 (539, 0.2706659809803833),
 (2403, 0.2655425022718972),
 (1201, 0.26554250227189713),
 (3723, 0.25715142542972574),
 (778, 0.2466466911319812),
 (582, 0.23750843439814176),
 (61, 0.22880215766121476),
 (1191, 0.22880215766121476),
 (2327, 0.22875450543583872),
 (4041, 0.22489899383695006),
 (1914, 0.21977383072747692),
 (1086, 0.21618989813247),
 (2780, 0.21571674297647797),
 (972, 0.21182963643408081),
 (942, 0.21021382614017325),
 (172, 0.20483662259967567),
 (151, 0.20483662259967564),
 (322, 0.20254787341673336),
 (4185, 0.20033416898825335),
 (1438, 0.20016019225635892),
 (2966, 0.20016019225635892),
 (3603, 0.20016019225635892),
 (260, 0.19814848097530424),
 (220, 0.19814848097530421),
 (74, 0.19795764159656265),
 (3667, 0.19535451620220173),
 (184, 0.1953545162022017),
 (47, 0.19277164398874672),
 (577, 0.18946618668626833),
 (27, 0.18923271008903098),
 (3157, 0.18923271008903098),
 (1198, 0.18842228790639834),
 (4, 0.18685673434682065),
 (91, 0.18681617943926832),
 (4399, 0.18490006540840973),
 (495, 0.1849000654084097),
 (305, 0.18452078282356416),
 (94, 0.1815682598006407),
 (1068, 0.17948717948717946),
 (2994, 0.17902871850985821),
 (3322, 0.17902871850985821),
 (1272, 0.17841031003501576),
 (1326, 0.17841031003501576),
 (83, 0.17764623667373097),
 (3992, 0.1754116038614058),
 (168, 0.17295817388759027),
 (1652, 0.17255919256291524),
 (4330, 0.17093520167692652),
 (1324, 0.17069718549972973),
 (1318, 0.1706971854997297),
 (838, 0.16984155512168939),
 (931, 0.16984155512168933),
 (300, 0.16898159235484367),
 (2198, 0.16898159235484367),
 (3533, 0.16898159235484367),
 (122, 0.16724840200141816),
 (36, 0.167093470609201),
 (373, 0.16694514082354447),
 (2578, 0.16694514082354447),
 (661, 0.16401847362094593),
 (1825, 0.16349964255346808),
 (505, 0.1634301126151534),
 (67, 0.16239958858823),
 (1976, 0.16239958858823),
 (529, 0.16178755723235852),
 (150, 0.1611258466588724),
 (668, 0.16012815380508716),
 (41, 0.1601281538050871),
 (1531, 0.1585187847802434),
 (342, 0.15818713475337637),
 (46, 0.15794943794779692),
 (595, 0.15695698526580623),
 (843, 0.15585730003983933),
 (4003, 0.15534712747612348),
 (31, 0.15408338784034142),
 (33, 0.15408338784034142),
 (773, 0.15408338784034142),
 (2509, 0.15408338784034142),
 (187, 0.15384615384615383),
 (1175, 0.15384615384615383),
 (2175, 0.15384615384615383),
 (149, 0.15202972471705734),
 (2725, 0.1513068831672006),
 (26, 0.14824986333222023),
 (1341, 0.14824986333222023),
 (2444, 0.14824986333222023),
 (2754, 0.147180996735913),
 (1001, 0.14617633655117152),
 (111, 0.14484136487558028),
 (311, 0.14484136487558028),
 (4090, 0.14484136487558028),
 (579, 0.1437993271357627),
 (581, 0.1437993271357627),
 (2069, 0.1437993271357627),
 (1473, 0.14351616441832768),
 (513, 0.1432229748078866),
 (7, 0.14322297480788657),
 (52, 0.14322297480788657),
 (127, 0.14322297480788657),
 (627, 0.14322297480788657),
 (1294, 0.14322297480788657),
 (1377, 0.14322297480788657),
 (108, 0.1416576493949657),
 (292, 0.14153462926807445),
 (2735, 0.14153462926807445),
 (1390, 0.14121975762272052),
 (1053, 0.1401425507601155),
 (1932, 0.1401425507601155),
 (461, 0.13937366833451514),
 (2490, 0.13937366833451514),
 (278, 0.1386750490563073),
 (1270, 0.1386750490563073),
 (1352, 0.1386750490563073),
 (294, 0.1373087590952724),
 (3349, 0.1373087590952724),
 (95, 0.13725270326150324),
 (454, 0.13725270326150324),
 (17, 0.13693937303317935),
 (466, 0.13655774839978377),
 (624, 0.13655774839978377),
 (1959, 0.13592873654160803),
 (275, 0.13533299049019168),
 (413, 0.13533299049019168),
 (568, 0.13533299049019168),
 (2163, 0.13533299049019168),
 (243, 0.1345345587992625),
 (4532, 0.1345345587992625),
 (56, 0.13355611265883557),
 (490, 0.13355611265883557),
 (1482, 0.13355611265883557),
 (3975, 0.13355611265883557),
 (121, 0.13344012817090595),
 (232, 0.13344012817090595),
 (1802, 0.13344012817090595),
 (1412, 0.13323467750529824),
 (4342, 0.13323467750529824),
 (1319, 0.13302600912742518),
 (502, 0.1319717610643751),
 (126, 0.1316245316231641),
 (859, 0.1316245316231641),
 (249, 0.1307440900921227),
 (2372, 0.1307440900921227),
 (3774, 0.1307440900921227),
 (4191, 0.1307440900921227),
 (777, 0.13074409009212268),
 (72, 0.12988108336653278),
 (3404, 0.12988108336653278),
 (4072, 0.12988108336653278),
 (158, 0.12955005512625914),
 (2127, 0.12955005512625914),
 (4347, 0.1283881477532739),
 (1554, 0.1282051282051282),
 (476, 0.12810252304406972),
 (935, 0.12810252304406972),
 (1298, 0.12810252304406972),
 (1367, 0.12810252304406972),
 (4011, 0.12810252304406972),
 (740, 0.12725695259515554),
 (369, 0.12659242088545833),
 (1012, 0.12659242088545833),
 (1765, 0.12659242088545833),
 (2680, 0.12659242088545833),
 (3617, 0.12659242088545833),
 (4223, 0.12659242088545833),
 (2867, 0.126155140059354),
 (134, 0.12561485860426555),
 (1768, 0.12561485860426555),
 (138, 0.12503908082008885),
 (1083, 0.12503908082008883),
 (3623, 0.12503908082008883),
 (1490, 0.12403473458920845),
 (14, 0.1235415527768502),
 (937, 0.1235415527768502),
 (368, 0.12326671027227314),
 (1827, 0.12326671027227314),
 (2646, 0.12326671027227314),
 (1735, 0.12301385521570944),
 (754, 0.1220965726263761),
 (166, 0.12209657262637608),
 (84, 0.12201777521731262),
 (208, 0.12104550653376048),
 (487, 0.12104550653376048),
 (1155, 0.12104550653376048),
 (102, 0.12104550653376046),
 (1449, 0.12104550653376046),
 (557, 0.1207011373963169),
 (3230, 0.1207011373963169),
 (1872, 0.12009611535381536),
 (1667, 0.12009611535381534),
 (2474, 0.12009611535381534),
 (1296, 0.11935247900657216),
 (266, 0.11935247900657214),
 (438, 0.11935247900657214),
 (1093, 0.11894020669001051),
 (2054, 0.11894020669001051),
 (3371, 0.11894020669001051),
 (4667, 0.11894020669001051),
 (999, 0.11737660545701085),
 (68, 0.11694106924093722),
 (483, 0.11694106924093722),
 (781, 0.11694106924093722),
 (2965, 0.11694106924093722),
 (549, 0.11678545896676293),
 (870, 0.11678545896676293),
 (1709, 0.11651034560709261),
 (2325, 0.11651034560709261),
 (2668, 0.11651034560709261),
 (2783, 0.11651034560709261),
 (139, 0.1165103456070926),
 (3714, 0.1165103456070926),
 (900, 0.11556254088025608),
 (1611, 0.11556254088025608),
 (422, 0.11503946170861017),
 (511, 0.11503946170861017),
 (678, 0.11503946170861017),
 (1271, 0.11503946170861017),
 (160, 0.11500161355436697),
 (182, 0.11437725271791938),
 (2278, 0.11437725271791938),
 (2541, 0.11437725271791938),
 (1491, 0.114022293537793),
 (3207, 0.11357879791107997),
 (589, 0.11322770341445959),
 (3078, 0.11322770341445959),
 (3993, 0.11322770341445959),
 (28, 0.11322770341445956),
 (1044, 0.11322770341445956),
 (85, 0.11265439490322912),
 (432, 0.11211213233271874),
 (228, 0.11211213233271873),
 (1217, 0.11211213233271873),
 (3142, 0.111687118657491),
 (23, 0.11149893466761211),
 (238, 0.11094003924504582),
 (889, 0.1104452707417832),
 (850, 0.11020775375559674),
 (1345, 0.11020775375559674),
 (1569, 0.11020775375559674),
 (536, 0.10997646755364593),
 (1506, 0.10997646755364593),
 (420, 0.10997646755364592),
 (3304, 0.10997646755364592),
 (50, 0.10984700727621793),
 (87, 0.10984700727621793),
 (786, 0.10984700727621793),
 (1610, 0.10984700727621793),
 (1939, 0.10984700727621793),
 (4462, 0.10984700727621793),
 (2366, 0.10895340841010223),
 (206, 0.10878565864408421),
 (1568, 0.10878565864408421),
 (236, 0.10826639239215334),
 (626, 0.10826639239215334),
 (1028, 0.10826639239215334),
 (3493, 0.10826639239215334),
 (81, 0.108094949066235),
 (229, 0.108094949066235),
 (262, 0.10795837927188263),
 (123, 0.10795837927188262),
 (215, 0.10795837927188262),
 (189, 0.10741723110591492),
 (256, 0.10741723110591492),
 (1518, 0.10741723110591492),
 (5, 0.10699012312772824),
 (270, 0.10699012312772824),
 (692, 0.10699012312772824),
 (2734, 0.10699012312772824),
 (3088, 0.10699012312772824),
 (3625, 0.10699012312772824),
 (21, 0.10675210253672475),
 (152, 0.10675210253672475),
 (227, 0.10675210253672475),
 (449, 0.10675210253672475),
 (2122, 0.10675210253672475),
 (2142, 0.10675210253672475),
 (3003, 0.10675210253672475),
 (3423, 0.10675210253672475),
 (4771, 0.10675210253672475),
 (307, 0.10639084227042908),
 (939, 0.10545808983558425),
 (203, 0.10529962529853128),
 (223, 0.10529962529853128),
 (242, 0.10529962529853128),
 (332, 0.10529962529853128),
 (341, 0.10529962529853128),
 (1234, 0.10529962529853128),
 (1741, 0.10529962529853128),
 (572, 0.105129283382795),
 (200, 0.10482848367219183),
 (653, 0.10482848367219183),
 (800, 0.10482848367219183),
 (1495, 0.10482848367219183),
 (2108, 0.10482848367219183),
 (2155, 0.10482848367219183),
 (472, 0.10390486669322622),
 (814, 0.10390486669322622),
 (1513, 0.10390486669322622),
 (2811, 0.10390486669322622),
 (467, 0.10336227882434038),
 (541, 0.10336227882434038),
 (75, 0.10256410256410256),
 (131, 0.10256410256410256),
 (687, 0.10256410256410256),
 (2066, 0.10256410256410256),
 (2492, 0.1025115460130912),
 (233, 0.10241831129983783),
 (1163, 0.10241831129983783),
 (1739, 0.10241831129983783),
 (2450, 0.10241831129983783),
 (2515, 0.10241831129983783),
 (4128, 0.10241831129983783),
 (3050, 0.10241831129983782),
 (654, 0.10168147934776052),
 (2433, 0.10168147934776052),
 (3898, 0.10168147934776052),
 (1192, 0.10127393670836667),
 (1608, 0.10127393670836667),
 (3147, 0.10127393670836667),
 (3335, 0.10127393670836667),
 (3629, 0.10127393670836667),
 (3867, 0.10127393670836667),
 (295, 0.10127393670836665),
 (170, 0.10087125544480038),
 (491, 0.10087125544480038),
 (2100, 0.10087125544480038),
 (105, 0.10016708449412667),
 (808, 0.10016708449412667),
 (1277, 0.10016708449412667),
 (2317, 0.10016708449412667),
 (3218, 0.10016708449412667),
 (3616, 0.10016708449412667),
 (3655, 0.10016708449412667),
 (3832, 0.10016708449412667),
 (3947, 0.10016708449412667),
 (2093, 0.10008009612817946),
 (312, 0.10003126465607107),
 (1034, 0.10003126465607107),
 (1079, 0.10003126465607107),
 (2241, 0.10003126465607107),
 (2911, 0.10003126465607107),
 (3748, 0.10003126465607107),
 (3436, 0.09930726528736966),
 (101, 0.09883324222148016),
 (4038, 0.09883324222148016),
 (1399, 0.09855206599818042),
 (1918, 0.09855206599818042),
 (2047, 0.09805806756909202),
 (2781, 0.09805806756909202),
 (4484, 0.09805806756909202),
 (363, 0.09781383788084239),
 (1433, 0.09781383788084239),
 (330, 0.09767725810110087),
 (508, 0.09767725810110087),
 (643, 0.09767725810110087),
 (1291, 0.09767725810110087),
 (3615, 0.09767725810110087),
 (3776, 0.09767725810110087),
 (3928, 0.09767725810110087),
 (10, 0.09656090991705352),
 (510, 0.09656090991705352),
 (898, 0.09656090991705352),
 (985, 0.09656090991705352),
 (230, 0.09638582199437336),
 (1769, 0.09638582199437336),
 (157, 0.09607689228305229),
 (263, 0.09607689228305229),
 (325, 0.09607689228305229),
 (1721, 0.09607689228305229),
 (1878, 0.09607689228305229),
 (1936, 0.09607689228305229),
 (2628, 0.09607689228305229),
 (2756, 0.09607689228305229),
 (4196, 0.09607689228305229),
 (4249, 0.09607689228305229),
 (4397, 0.09607689228305229),
 (4466, 0.09607689228305229),
 (410, 0.09548198320525772),
 (445, 0.09548198320525772),
 (535, 0.09548198320525772),
 (1106, 0.09548198320525772),
 (1817, 0.09548198320525772),
 (2235, 0.09548198320525772),
 (2247, 0.09548198320525772),
 (2550, 0.09548198320525772),
 (334, 0.09443843292997713),
 (371, 0.09443843292997713),
 (480, 0.09443843292997713),
 (587, 0.09443843292997713),
 (1354, 0.09443843292997713),
 (35, 0.09421114395319916),
 (267, 0.09421114395319916),
 (319, 0.09421114395319916),
 (715, 0.09421114395319916),
 (878, 0.09421114395319916),
 (1074, 0.09421114395319916),
 (1153, 0.09421114395319916),
 (1303, 0.09421114395319916),
 (2556, 0.09421114395319916),
 (18, 0.09370791409872918),
 (4539, 0.09370791409872918),
 (412, 0.09342836717341034),
 (1395, 0.09342836717341034),
 (1877, 0.09342836717341034),
 (1990, 0.09342836717341034),
 (2644, 0.09342836717341034),
 (301, 0.0930725988812425),
 (11, 0.09245003270420486),
 (473, 0.09245003270420486),
 (2482, 0.09245003270420486),
 (3713, 0.09245003270420486),
 (4012, 0.09245003270420486),
 (4496, 0.09245003270420486),
 (148, 0.09245003270420485),
 (216, 0.09245003270420485),
 (239, 0.09245003270420485),
 (1480, 0.09245003270420485),
 (1567, 0.09245003270420485),
 (1680, 0.09245003270420485),
 (1715, 0.09245003270420485),
 (4325, 0.09245003270420485),
 (9, 0.0915018021743355),
 (129, 0.0915018021743355),
 (543, 0.0915018021743355),
 (1686, 0.0915018021743355),
 (2586, 0.0915018021743355),
 (2814, 0.0915018021743355),
 (3402, 0.0915018021743355),
 (362, 0.09078412990032037),
 (791, 0.09078412990032037),
 (3729, 0.09078412990032037),
 (785, 0.09065471553673685),
 (596, 0.09058216273156766),
 (813, 0.09058216273156766),
 (1230, 0.09058216273156766),
 (1440, 0.09058216273156766),
 (1695, 0.09058216273156766),
 (1900, 0.09058216273156766),
 (4337, 0.09058216273156766),
 (2564, 0.09007912422186248),
 (3384, 0.08968970586617499),
 (3874, 0.08968970586617499),
 (219, 0.08920515501750789),
 (259, 0.08920515501750789),
 (356, 0.08920515501750789),
 (660, 0.08920515501750789),
 (1468, 0.08920515501750789),
 (1750, 0.08920515501750789),
 (2087, 0.08920515501750789),
 (2639, 0.08920515501750789),
 (2645, 0.08920515501750789),
 (2862, 0.08920515501750789),
 (3235, 0.08920515501750789),
 (3532, 0.08920515501750789),
 (799, 0.08896008544727063),
 (43, 0.0888231183368655),
 (994, 0.0888231183368655),
 (1273, 0.0888231183368655),
 (1275, 0.0888231183368655),
 (2357, 0.0888231183368655),
 (2790, 0.0888231183368655),
 (3457, 0.0888231183368655),
 (274, 0.08833906504195108),
 (331, 0.08798117404291673),
 (602, 0.08798117404291673),
 (1840, 0.08798117404291673),
 (2103, 0.08798117404291673),
 (12, 0.08770580193070292),
 (167, 0.08770580193070292),
 (244, 0.08770580193070292),
 (400, 0.08770580193070292),
 (920, 0.08770580193070292),
 (1024, 0.08770580193070292),
 (1474, 0.08770580193070292),
 (2654, 0.08770580193070292),
 (2952, 0.08770580193070292),
 (3317, 0.08770580193070292),
 (3443, 0.08770580193070292),
 (4265, 0.08770580193070292),
 (479, 0.08735706972682653),
 (2109, 0.08735706972682653),
 (169, 0.08716272672808179),
 (199, 0.08716272672808179),
 (212, 0.08716272672808179),
 (618, 0.08716272672808179),
 (2398, 0.08716272672808179),
 (2707, 0.08716272672808179),
 (3548, 0.08716272672808179),
 (63, 0.0863667034175061),
 (752, 0.0863667034175061),
 (1777, 0.0863667034175061),
 (2314, 0.0863667034175061),
 (2442, 0.08633531446374632),
 (88, 0.08627959628145762),
 (141, 0.08627959628145762),
 (794, 0.08627959628145762),
 (960, 0.08627959628145762),
 (977, 0.08627959628145762),
 (1256, 0.08627959628145762),
 (1402, 0.08627959628145762),
 (2245, 0.08627959628145762),
 (2390, 0.08627959628145762),
 (1524, 0.08559209850218259),
 (1826, 0.08559209850218259),
 (2850, 0.08559209850218259),
 (3551, 0.08559209850218259),
 (4510, 0.08559209850218259),
 (4581, 0.08559209850218259),
 (2, 0.08492077756084468),
 (142, 0.08492077756084468),
 (195, 0.08492077756084468),
 (457, 0.08492077756084468),
 (745, 0.08492077756084468),
 (1139, 0.08492077756084468),
 (1246, 0.08492077756084468),
 (2298, 0.08492077756084468),
 (2577, 0.08492077756084468),
 (3130, 0.08492077756084468),
 (3444, 0.08492077756084468),
 (143, 0.08483796839677037),
 (827, 0.08483796839677037),
 (234, 0.084103426706236),
 (1016, 0.084103426706236),
 (389, 0.08362420100070908),
 (564, 0.08362420100070908),
 (1421, 0.08362420100070908),
 (2985, 0.08362420100070908),
 (4554, 0.08362420100070908),
 (32, 0.08338763984501665),
 (217, 0.08338763984501665),
 (1633, 0.08338763984501665),
 (2348, 0.08338763984501665),
 (2963, 0.08338763984501665),
 (19, 0.0826898230594723),
 (190, 0.0826898230594723),
 (381, 0.0826898230594723),
 (1302, 0.0826898230594723),
 (3971, 0.0826898230594723),
 (4562, 0.0826898230594723),
 (4731, 0.0826898230594723),
 (1372, 0.08238525545716345),
 (1583, 0.08238525545716345),
 (1743, 0.08238525545716345),
 (3135, 0.08238525545716345),
 (2380, 0.0821440096816907),
 (48, 0.08200923681047297),
 (403, 0.08134518347820842),
 (591, 0.08134518347820842),
 (1188, 0.08134518347820842),
 (2197, 0.08134518347820842),
 (3555, 0.08134518347820842),
 (1094, 0.08119979429411502),
 (1, 0.081199794294115),
 (315, 0.081199794294115),
 (787, 0.081199794294115),
 (899, 0.081199794294115),
 (1682, 0.081199794294115),
 (2549, 0.081199794294115),
 (2655, 0.081199794294115),
 (2859, 0.081199794294115),
 (3252, 0.081199794294115),
 (45, 0.0806970043558403),
 (501, 0.0806970043558403),
 (2786, 0.0806970043558403),
 (39, 0.08006407690254357),
 (62, 0.08006407690254357),
 (164, 0.08006407690254357),
 (241, 0.08006407690254357),
 (534, 0.08006407690254357),
 (544, 0.08006407690254357),
 (547, 0.08006407690254357),
 (1136, 0.08006407690254357),
 (1266, 0.08006407690254357),
 (1615, 0.08006407690254357),
 (1692, 0.08006407690254357),
 (2871, 0.08006407690254357),
 (2874, 0.08006407690254357),
 (3175, 0.08006407690254357),
 (3213, 0.08006407690254357),
 (3296, 0.08006407690254357),
 (3465, 0.08006407690254357),
 (3522, 0.08006407690254357),
 (3919, 0.08006407690254357),
 (4273, 0.08006407690254357),
 (4467, 0.08006407690254357),
 (4486, 0.08006407690254357),
 (4620, 0.08006407690254357),
 (4648, 0.08006407690254357),
 (4651, 0.08006407690254357),
 (38, 0.07944581222989573),
 (812, 0.07944581222989573),
 (245, 0.07897471897389846),
 (306, 0.07897471897389846),
 (402, 0.07897471897389846),
 (775, 0.07897471897389846),
 (894, 0.07897471897389846),
 (901, 0.07897471897389846),
 (1204, 0.07897471897389846),
 (1784, 0.07897471897389846),
 (2638, 0.07897471897389846),
 (3809, 0.07897471897389846),
 (3844, 0.07897471897389846),
 (4748, 0.07897471897389846),
 (103, 0.07884165279854434),
 (1528, 0.07884165279854434),
 (4500, 0.07884165279854434),
 (486, 0.07850928662766596),
 (51, 0.0782510703046739),
 (222, 0.0782510703046739),
 (1822, 0.0782510703046739),
 (37, 0.07792865001991967),
 (70, 0.07792865001991967),
 (98, 0.07792865001991967),
 (1322, 0.07792865001991967),
 (2161, 0.07792865001991967),
 (2289, 0.07792865001991967),
 (2677, 0.07792865001991967),
 (3097, 0.07792865001991967),
 (3757, 0.07792865001991967),
 (4335, 0.07792865001991967),
 (193, 0.07776510597812535),
 (251, 0.07767356373806174),
 (584, 0.07767356373806174),
 (866, 0.07767356373806174),
 (1180, 0.07767356373806174),
 (1920, 0.07767356373806174),
 (2665, 0.07767356373806174),
 (3121, 0.07767356373806174),
 (3425, 0.07767356373806174),
 (3500, 0.07767356373806174),
 (3721, 0.07767356373806174),
 (153, 0.07710865759549869),
 (1892, 0.07710865759549869),
 (16, 0.07692307692307693),
 (86, 0.07692307692307693),
 (854, 0.07692307692307693),
 (1158, 0.07692307692307693),
 (1542, 0.07692307692307693),
 (2443, 0.07692307692307693),
 (2933, 0.07692307692307693),
 (3023, 0.07692307692307693),
 (3159, 0.07692307692307693),
 (3798, 0.07692307692307693),
 (4310, 0.07692307692307693),
 (286, 0.07655590023509527),
 (1653, 0.07655590023509527),
 (329, 0.075955452531275),
 (922, 0.075955452531275),
 (1003, 0.075955452531275),
 (1077, 0.075955452531275),
 (1286, 0.075955452531275),
 (2218, 0.075955452531275),
 (3086, 0.075955452531275),
 (4261, 0.075955452531275),
 (4552, 0.075955452531275),
 (4618, 0.075955452531275),
 (1042, 0.07548513560963972),
 (1279, 0.07548513560963972),
 (1658, 0.07548513560963972),
 (2268, 0.07548513560963972),
 (2333, 0.07548513560963972),
 (2706, 0.07548513560963972),
 (3825, 0.07548513560963972),
 (4004, 0.07548513560963972),
 (4158, 0.07548513560963972),
 (112, 0.07502344849205331),
 (174, 0.07502344849205331),
 (207, 0.07502344849205331),
 (492, 0.07502344849205331),
 (631, 0.07502344849205331),
 (1110, 0.07502344849205331),
 (1517, 0.07502344849205331),
 (2213, 0.07502344849205331),
 (3228, 0.07502344849205331),
 (125, 0.07479575920067656),
 (1999, 0.074458079104994),
 (2250, 0.074458079104994),
 (3326, 0.07433762918125657),
 (40, 0.07412493166611012),
 (82, 0.07412493166611012),
 (96, 0.07412493166611012),
 (235, 0.07412493166611012),

In [250]:
def recommend(movie):
    # Find the index of the movie
    movie_index = new_df[new_df['title'] == movie].index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Get top 7 most similar movies (excluding the first one which is the same movie)
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:7]

    # Print recommended movie indexes or titles
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [254]:
recommend('Avatar')

Aliens vs Predator: Requiem
Independence Day
Titan A.E.
Aliens
Predators
Falcon Rising

In [256]:
import pickle

In [264]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [266]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [268]:
new_df.head()

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict in the 22n...
1,285,Pirates of the Caribbean: At World's End,"adventur fantasi action captain barbossa, long..."
2,206647,Spectre,action adventur crime a cryptic messag from bo...
3,49026,The Dark Knight Rises,action crime drama thriller follow the death o...
4,49529,John Carter,action adventur sciencefict john carter is a w...